/// Based on standard cost.
table Sales
	lineageTag: c90c54c3-ecc7-4006-acae-213e629b2b9e

	measure Profit =
			
			SUM('Sales'[Sales]) - SUM('Sales'[Cost])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: e9392e16-8287-4a63-8f98-14ddbc88ec6d

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MathematicalSubtraction"
				}

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Profit Margin' =
			
			DIVIDE([Profit], SUM('Sales'[Sales]))
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: 6dcf0ce0-a21f-454e-8857-7bf5e2b7b031

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MathematicalDivision"
				}

		changedProperty = FormatString

	measure 'Avg Price' =
			
			AVERAGE(Sales[Unit Price])
		formatString: #,0.00
		displayFolder: Pricing
		lineageTag: 2d88e895-a8d8-4dca-9933-8ea742fb3430

	measure 'Median Price' =
			
			MEDIAN(Sales[Unit Price])
		formatString: #,0.00
		displayFolder: Pricing
		lineageTag: 8447aefd-40c0-4102-957b-dbfbf844ec5d

	measure 'Min Price' = ```
			
			MIN(Sales[Unit Price])
			
			```
		formatString: #,0.00
		displayFolder: Pricing
		lineageTag: 97a0ff5e-d73c-4dcb-b5db-8b2e291f7002

	measure 'Max Price' =
			
			MAX(Sales[Unit Price])
		formatString: #,0.00
		displayFolder: Pricing
		lineageTag: bcb257b8-5467-4f56-9628-53b435824075

	measure Orders =
			
			DISTINCTCOUNT(Sales[SalesOrderNumber])
		formatString: #,0.00
		displayFolder: Counts
		lineageTag: a4eaea9b-48cb-48e6-a3b9-61248e287be4

	measure 'Order Lines' =
			
			COUNTROWS(Sales)
		formatString: #,0.00
		displayFolder: Counts
		lineageTag: 3fedc907-3be2-4517-acc4-c250c1a5a011

	column SalesOrderNumber
		dataType: string
		isHidden
		lineageTag: f7a951a1-052d-44bb-911c-0f487977d8e6
		summarizeBy: none
		sourceColumn: SalesOrderNumber

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: f09e25ae-d1b9-4233-80a0-f947efe49834
		summarizeBy: none
		sourceColumn: OrderDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ProductKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 322e241e-6244-4cd7-bb79-bf30ad967c85
		summarizeBy: none
		sourceColumn: ProductKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ResellerKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: fa69a045-873a-49b5-847a-2eda5565fab7
		summarizeBy: none
		sourceColumn: ResellerKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column EmployeeKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 84ab0fd3-0c83-4456-a495-f0e3817be1b3
		summarizeBy: none
		sourceColumn: EmployeeKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SalesTerritoryKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e2190568-d580-4d50-abaf-e366040afd52
		summarizeBy: none
		sourceColumn: SalesTerritoryKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		formatString: #,0
		lineageTag: 1f8ac87e-c2b3-4d8f-bf03-f927b297974e
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'Unit Price'
		dataType: decimal
		isHidden
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 914c5056-0675-4279-90b9-9b47f4096186
		summarizeBy: average
		sourceColumn: Unit Price

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Sales
		dataType: decimal
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 4465de7d-4f58-462b-8ddb-6207fcce0d92
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	/// Based in standard cost
	column Cost
		dataType: decimal
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 4891cf60-2811-4a99-9d25-63cb318cbb38
		summarizeBy: sum
		sourceColumn: Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	partition Sales = m
		mode: import
		source =
				let
				    Source = Sql.Databases(SQLInstance),
				    AdventureWorksDW2020 = Source{[Name=Database]}[Data],
				    dbo_FactResellerSales = AdventureWorksDW2020{[Schema="dbo",Item="FactResellerSales"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(dbo_FactResellerSales,{"SalesOrderNumber", "OrderDate", "ProductKey", "ResellerKey", "EmployeeKey", "SalesTerritoryKey", "OrderQuantity", "UnitPrice", "TotalProductCost", "SalesAmount", "DimProduct"}),
				    #"Expanded DimProduct" = Table.ExpandRecordColumn(#"Removed Other Columns", "DimProduct", {"StandardCost"}, {"StandardCost"}),
				    #"Added Custom" = Table.AddColumn(#"Expanded DimProduct", "Cost", each if [TotalProductCost] = null then [OrderQuantity] * [StandardCost] else [TotalProductCost]),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Custom",{"StandardCost", "TotalProductCost"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"Cost", type number}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"OrderQuantity", "Quantity"}, {"UnitPrice", "Unit Price"}, {"SalesAmount", "Sales"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns",{{"Quantity", Int64.Type}, {"Unit Price", Currency.Type}, {"Sales", Currency.Type}, {"Cost", Currency.Type}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

